[package]
name = "mahf-coco"
version = "0.1.0"
authors = ["Leopold Luley <git@leopoldluley.de>"]
edition = "2021"

[dependencies]
mahf = "0.1"
coco-rs = "0.6"
serde = { version = "1.0.131", features = ["derive"] }
anyhow = "1.0.71"
scoped_threadpool = "0.1.9"
better_any = "0.2.0"
